DESCRIPTION = "Chromium is an open-source browser project that aims to build a safer, faster, and more stable way for all users to experience the web."
HOMEPAGE = "https://www.chromium.org/Home"
SRC_URI = "https://commondatastorage.googleapis.com/chromium-browser-official/${BP}.tar.xz"

LICENSE = "BSD-3-Clause"

LIC_FILES_CHKSUM = "\
    file://${S}/LICENSE;md5=0fca02217a5d49a14dfe2d11837bb34d \
     "

SRC_URI[md5sum] = "9c1c9aefe72876865800952c20b25d5e"
SRC_URI[sha256sum] = "a194ae1edb041024b3d4b6ba438f32fefdb6f1ecb24a96c50248a486b237a101"
